packages:
  - "packages/*"

# Native build/post-install scripts we trust.
allowBuilds:
  "@prisma/client": true
  "@prisma/engines": true
  "@scarf/scarf": false
  argon2: true
  esbuild: true
  prisma: true
